name: CCDK CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci || true
      - name: Lint
        run: npm run lint --if-present || echo "No linter"
      - name: Tests
        run: npm test --if-present || echo "No tests"
  build-docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs
        run: pip install mkdocs mkdocs-material
      - name: Build docs
        run: mkdocs build -d site
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
